# This section details the defaul basebox configuration.
# You should edit this.
default: &default
  ip: 192.168.200.1
  orgname: github.com
  vbox: debian-6.0.6-amd64
  memory_size: 512
# But don't edit this unless you know what you're doing.
puppetmaster:
  <<: *default
  ip: 192.168.200.2
  memory_size: 1024
  mounts:
    puppet_manifests:
      guest: /etc/puppet/manifests
      host: ~/github/puppet/manifests
    puppet_modules:
      guest: /etc/puppet/modules
      host: ~/github/puppet/modules
    hitch_config:
      guest: /etc/vagrant/hitch
      host: ./config
  puppet:
